version: '3.8'
services:
    app:
        image: node:15.6.0
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3001:3001
        volumes:
            - './:/app'
        environment:
            - CHOKIDAR_USEPOLLING=true
