version: "3.8"
services:
  app:
    container_name: anovote_frontend
    image: anovote:frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules:
